### ISSUE TITLE
BUG: Failed to load a language-legesher-python package grammar

### ISSUE THREAD

**Issue by madiedgar** [legesher/language-legesher-python#33]
[Enter steps to reproduce:]

1. Install package on Atom
2. Disable language-python in Atom packages
3. Enable language-legesher-python in Atom packages
4. Restart Atom (error will pop up upon opening)

**Atom**: 1.48.0 x64
**Electron**: 5.0.13
**OS**: Mac OS X 10.15.4
**Thrown From**: [language-legesher-python](https://github.com/legesher/language-legesher-python) package 0.58.2

### Stack Trace

Failed to load a language-legesher-python package grammar

```
At The module '/Users/../.atom/packages/language-legesher-python/node_modules/tree-sitter-legesher-python/build/Release/tree_sitter_python_legesher_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 69. This version of Node.js requires
NODE_MODULE_VERSION 70. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`). in /Users/../.atom/packages/language-legesher-python/grammars/tree-sitter-legesher-python.cson

Error: The module '/Users/../.atom/packages/language-legesher-python/node_modules/tree-sitter-legesher-python/build/Release/tree_sitter_python_legesher_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 69. This version of Node.js requires
NODE_MODULE_VERSION 70. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (electron/js2c/asar.js:138:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:881:18)
    at Object.func [as .node] (electron/js2c/asar.js:138:31)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146819)
    at /packages/language-legesher-python/node_modules/tree-sitter-legesher-python/index.js:2:20)
    at /packages/language-legesher-python/node_modules/tree-sitter-legesher-python/index.js:15:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147503)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:151051)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:14:16)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:695414)
    at new TreeSitterGrammar (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3114871)
    at GrammarRegistry.createGrammar (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:360441)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:360282
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:582168
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:54:3)
  at /packages/language-legesher-python/grammars/tree-sitter-legesher-python.cson:1:1
```

### Commands

```
```

### Non-Core Packages

```
autocomplete-emojis 2.5.0 
busy-signal 2.0.1 
file-icons 2.1.41 
intentions 1.1.5 
language-legesher-python 0.58.2 
linter 2.3.1 
linter-eslint 8.5.5 
linter-htmlhint 1.6.3 
linter-python 3.1.2 
linter-ruby 1.3.1 
linter-spell 0.15.0 
linter-spell-html 0.7.0 
linter-ui-default 1.8.1 
pigments 0.40.2 
prettier-atom 0.60.1 
```

**Comment by madiedgar** [comment]
This issue was resolved in version 0.58.3 🎉
