### ISSUE TITLE
Failed to load a language-legesher-python package grammar

### ISSUE THREAD

**Issue by madiedgar** [legesher/language-legesher-python#9]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.39.0 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.5
**Thrown From**: [language-legesher-python](https://github.com/legesher/language-legesher-python) package 0.56.0

### Stack Trace

Failed to load a language-legesher-python package grammar

```
At The module '/Users/madisonedgar/.atom/packages/language-legesher-python/node_modules/tree-sitter-legesher-python/build/Release/tree_sitter_legesher_python_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`). in /Users/madisonedgar/.atom/packages/language-legesher-python/grammars/tree-sitter-legesher-python.cson

Error: The module '/Users/madisonedgar/.atom/packages/language-legesher-python/node_modules/tree-sitter-legesher-python/build/Release/tree_sitter_legesher_python_binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:166:20)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:71:46)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146719)
    at /packages/language-legesher-python/node_modules/tree-sitter-legesher-python/index.js:2:20)
    at /packages/language-legesher-python/node_modules/tree-sitter-legesher-python/index.js:11:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147410)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150958)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:71:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:686763)
    at new TreeSitterGrammar (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3344094)
    at GrammarRegistry.createGrammar (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:359235)
    at l.readFile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:359076)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:580572
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:440:3)
  at /packages/language-legesher-python/grammars/tree-sitter-legesher-python.cson:1:1
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
autocomplete-emojis 2.5.0 
language-legesher-python 0.56.0 
```

**Comment by madiedgar** [comment]
not getting this consistently // not sure how to reproduce - logged this for future reference
